<a href="https://colab.research.google.com/github/naomori/codexa_Numpy_Introduction/blob/master/Chapter8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 行列の演算と処理



# 逆行列

A が m x m として、逆行列が存在するとき

In [0]:
import numpy as np

In [3]:
a = np.array([[2,5], [1,3]])
a

array([[2, 5],
       [1, 3]])

In [4]:
b = np.linalg.inv(a)
b

array([[ 3., -5.],
       [-1.,  2.]])

In [5]:
np.dot(a, b)

array([[1., 0.],
       [0., 1.]])

# 転置行列

Transposed Matrix

In [6]:
c = np.array([[3,1], [2,6], [4,5]])
c

array([[3, 1],
       [2, 6],
       [4, 5]])

In [7]:
c.T

array([[3, 2, 4],
       [1, 6, 5]])

In [8]:
a

array([[2, 5],
       [1, 3]])

In [9]:
a.T

array([[2, 1],
       [5, 3]])

## 対角成分(diagonal)の取得

np.diag()で取得できる

In [10]:
d = np.array([[1,0,0], [0,1,0], [0,0,1]])
d

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [11]:
np.diag(d)

array([1, 1, 1])

# ベクトルの外積と内積

* 内積(inner)：スカラー積
* 外積(outer)：ベクトル積

In [13]:
a = np.array([1,2,3,4])
print(a)
b = np.array([5,6,7,8])
print(b)

[1 2 3 4]
[5 6 7 8]


In [14]:
np.inner(a, b)

70

In [15]:
np.outer(a, b)

array([[ 5,  6,  7,  8],
       [10, 12, 14, 16],
       [15, 18, 21, 24],
       [20, 24, 28, 32]])

In [16]:
c = np.array([0,2,4,7])
np.outer(c, b)

array([[ 0,  0,  0,  0],
       [10, 12, 14, 16],
       [20, 24, 28, 32],
       [35, 42, 49, 56]])