<a href="https://colab.research.google.com/github/naomori/codexa_Numpy_Introduction/blob/master/Chapter6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 行列の積

$\begin{pmatrix}
a & b \\
c & d 
\end{pmatrix} \times
\begin{pmatrix}
e & f \\
g & h
\end{pmatrix} = 
\begin{pmatrix}
ae + bg & af + bh \\
ce + dg & cf + dh
\end{pmatrix}$

In [0]:
import numpy as np

In [2]:
a = np.array([[1,2], [3,4]])
a

array([[1, 2],
       [3, 4]])

In [3]:
b = np.array([[6,7], [8,9]])
b

array([[6, 7],
       [8, 9]])

# アダマール積
各要素の掛け算のこと

In [4]:
a * b

array([[ 6, 14],
       [24, 36]])

# 内積
* 順番が違うと結果が同じにならないことがある

In [5]:
np.dot(a, b)

array([[22, 25],
       [50, 57]])

In [6]:
np.dot(b, a)

array([[27, 40],
       [35, 52]])

In [7]:
a.dot(b)

array([[22, 25],
       [50, 57]])

In [8]:
b.dot(a)

array([[27, 40],
       [35, 52]])

# Python.List から Numpy.Array への変換
* np.array()の引数にListを渡すだけで変換できる
* Python.List にするには .tolist() で変換できる

In [10]:
c = [[1,2], [3,4]]
c
type(c)

list

In [11]:
c = np.array(c)
c
type(c)

numpy.ndarray

In [14]:
d = [[1,2,3,4,5], [2,3]]
type(d)

list

In [15]:
d

[[1, 2, 3, 4, 5], [2, 3]]

In [13]:
d = np.array(d)
type(d)

numpy.ndarray

In [16]:
d

[[1, 2, 3, 4, 5], [2, 3]]

In [18]:
c = c.tolist()
type(c)

list