<a href="https://colab.research.google.com/github/naomori/codexa_Numpy_Introduction/blob/master/Chapter4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy配列

* np.array()で作成
* type は np.ndarray
* np.shape()で配列の形を見れる
* and more...

In [0]:
import numpy as np

In [3]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [4]:
type(a)

numpy.ndarray

In [5]:
a.shape

(3,)

In [6]:
a.dtype

dtype('int64')

In [7]:
a[0]

1

In [8]:
a[1]

2

In [10]:
b = np.array([[1,2,3], [4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
b.shape

(2, 3)

In [13]:
b.dtype

dtype('int64')

In [14]:
b[0]

array([1, 2, 3])

In [15]:
b[1]

array([4, 5, 6])

In [16]:
b[0][0]

1

In [17]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
b[1][0]

4

In [19]:
b[0, 0]

1

In [20]:
b[1,0]

4

In [21]:
c = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [22]:
c.shape

(3, 4)

In [23]:
c.dtype

dtype('int64')

In [24]:
c[:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [25]:
c[2:]

array([[ 9, 10, 11, 12]])

In [26]:
c[:2, 1]

array([2, 6])

In [27]:
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [28]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [29]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [30]:
np.full((3,5), 10)

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [31]:
# eye = Identity Matrix (単位行列)のこと
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])