<a href="https://colab.research.google.com/github/naomori/codexa_Numpy_Introduction/blob/master/Chapter7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 乱数の生成


# 一様乱数：0-1の一様分布の乱数

In [0]:
import numpy as np

In [4]:
np.random.rand(10)

array([0.12579552, 0.11580811, 0.05638604, 0.19575645, 0.62927097,
       0.62366157, 0.13284304, 0.25238773, 0.20047705, 0.28401145])

In [10]:
a = np.random.rand(2, 2)
a

array([[0.77231703, 0.31208797],
       [0.76716008, 0.60442852]])

In [11]:
a.shape

(2, 2)

## 標準正規分布（Standard Normal Distribution）

* 標準偏差(standard deviation)=1
* 平均値(mean) = 0

In [7]:
import numpy as np
np.random.randn(1)

array([1.37070535])

In [8]:
randn5000 = np.random.randn(5000,5000)
randn5000.shape

(5000, 5000)

In [9]:
randn5000.mean()

0.00010167184230085684

In [10]:
randn5000_2 = np.random.randn(5000,5000)
randn5000_2.shape
randn5000_2.mean()

0.00012860721761759296

In [11]:
randn5000.std()

1.0000595432960229

# 整数の乱数

* np.random.randint()で整数の乱数を生成できる

In [14]:
np.random.randint(100)

75

In [15]:
np.random.randint(1,30,30)

array([20, 15,  1, 15,  2, 14, 29, 23, 10, 26, 21, 19, 14,  4, 26, 15, 29,
       19, 11,  4,  1, 14, 15, 14, 21, 20, 17, 22, 15, 24])

In [18]:
randint30 = np.random.randint(1,30,(30,30))
print(randint30)
print(randint30.shape)

[[ 9 15  3 10 16 13  8 13  1 10 22 13  7 13 20 18  2 22  5 25 15 24 28  2
   8 20 28  8 10 16]
 [23 27 24  1 11  3 16 21 29 23  5  1  6 10 13 24 28  5 14  5 15  2 27 14
  27 28 13  5  2  6]
 [26  6 11 27  8 25 28 19 18 21 17  1  9 19  4  5 18 16 17 14 26 13 20 17
   7 22  3 24  2  9]
 [12  3 18 19 12 13 26  8 10  3  6 13 29  8 22  7 26 17 24  3 17  6 25 13
  27 18  9 18 12  2]
 [16  6 28 16  8  3 20 20  1 16 23 11 18 23 18 21 18 27 17 12 25  8  8 21
  12 20  3  8 11  4]
 [ 8 22 14 13  2  1 29 28 11 16 24 15  9 29 20 26  4  2 28 20  3 12  4 22
  24  3 29  1 28 20]
 [ 8  6  4  2  8  4 20 28 25  6 12 22 24 18 20 10 28 23 26 25 18 10  1  3
  20  8  9  9  7  9]
 [23 25  6  5 22 12 12 28 29  3  2 23 17 11 28 26 22 19 15 16  1 18 13 19
  11 11 22 29 16 23]
 [11 15 17 20 29  6 17  3 11 25 17 20  5 16 25 16 26 24 25 17 28 10  7 11
  29 22 27 22 21 29]
 [29 27 13 16 19 12  1 21 17 10 15 14 25 16  6  4 14 10 24  9  7  9  8  6
   8  8  7 12 11 13]
 [ 6  8 11 20  7 25 17 20 19  9  6 12  8 19  3 28 

# Seed の使い方

In [0]:
np.random.seed(100)

In [20]:
np.random.randn()

-1.7497654730546974

In [21]:
np.random.randn()

0.34268040332750216

In [22]:
np.random.randn()

1.153035802563644

In [23]:
np.random.randn()

-0.25243603652138985

In [0]:
np.random.seed(100)

In [25]:
np.random.randn()

-1.7497654730546974