<a href="https://colab.research.google.com/github/naomori/codexa_Numpy_Introduction/blob/master/Chapter9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 数学系の関数

* sin, cosin, tan
* e: 自然対数
* exponential function: 指数関数
* log: 対数関数

In [0]:
import numpy as np

In [2]:
# 引数は度数ではなくラジアンのため、1にはならない。
np.tan(45)

1.6197751905438615

In [3]:
# np.radians()で度数からtangentに変換できる
rd = np.radians(45)
rd

0.7853981633974483

In [4]:
np.tan(rd)

0.9999999999999999

In [6]:
rd = np.radians(90)
np.sin(rd)

1.0

In [7]:
np.e

2.718281828459045

In [8]:
np.exp(2)

7.38905609893065

In [9]:
a = np.array([1,2,3,4,5])
np.exp(a)

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

In [10]:
np.log(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [0]:
b = np.array([-5,-1,-1,0,10,15,-1,2])

In [13]:
# sign()によって、符号のみにできる
np.sign(b)

array([-1, -1, -1,  0,  1,  1, -1,  1])

In [14]:
c = np.random.randn(10)
c

array([ 2.50503983,  0.34724715, -0.04797436,  0.22300869,  1.05255345,
       -2.84883989, -1.27016646,  0.11500399, -0.23296138, -0.25713124])

np.rint()は小数点以下を四捨五入

In [16]:
np.rint(c)

array([ 3.,  0., -0.,  0.,  1., -3., -1.,  0., -0., -0.])

In [17]:
# 小数部分と整数部分を分けて、配列に格納する
np.modf(c)

(array([ 0.50503983,  0.34724715, -0.04797436,  0.22300869,  0.05255345,
        -0.84883989, -0.27016646,  0.11500399, -0.23296138, -0.25713124]),
 array([ 2.,  0., -0.,  0.,  1., -2., -1.,  0., -0., -0.]))