<a href="https://colab.research.google.com/github/naomori/codexa_Numpy_Introduction/blob/master/Chapter5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Chapter.5: 基本的な演算

* Python List と Numpy Array は異なる
* Numpy Array は行列、一次元はベクトルとして扱われる

In [0]:
import numpy as np

In [2]:
a = np.array([[1,2,3], [4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
b = np.array([[1,2,3], [4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
a + b

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [5]:
a - b

array([[0, 0, 0],
       [0, 0, 0]])

In [6]:
a * 2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [7]:
a ** 2

array([[ 1,  4,  9],
       [16, 25, 36]])

In [8]:
a / 2

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ]])

In [9]:
a < 2

array([[ True, False, False],
       [False, False, False]])

In [12]:
array = np.array([1,2,3])
array

array([1, 2, 3])

In [13]:
list = [1,2,3]
list

[1, 2, 3]

In [14]:
list + [4]

[1, 2, 3, 4]

In [15]:
array + [4]

array([5, 6, 7])

In [16]:
array

array([1, 2, 3])

In [17]:
list2 = []
for e in list:
  list2.append(e + 4)
list2

[5, 6, 7]

In [18]:
list

[1, 2, 3]

In [19]:
list * 2

[1, 2, 3, 1, 2, 3]

In [20]:
array * 2

array([2, 4, 6])

In [21]:
list2 = []
for e in list:
  list2.append(e*2)
list2

[2, 4, 6]

In [22]:
list

[1, 2, 3]